name: asd-gwas
channels:
  - conda-forge
  - kaspermunch
  - gwforg
  - micknudsen
  - r  
  - defaults
dependencies:
  - jupyterlab
  - nodejs
  - pytables
  - scipy
  - seaborn
  - slurm-jupyter
  - statsmodels
  - geneinfo
  - git
  - nbdime
  - gwf
  - gwf-utilization

